project:
  type: website
  output-dir: docs

website:
  title: "Md Saidul Hoque Anik"
  description: "Md Saidul Hoque Anik is a graduate student working at the intersection of high performance computing and graph neural networks."
  
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research
        text: Research
      - href: news
        text: News
      - href: teaching
        text: Teaching
      - text: More
        menu:
            - href: "/leadership/"
              text: Leadership
            - href: software
              text: Software
            - href: "/news/#category=Publication"
              text: Publications
            - href: blog
              text: Blog
      

format:
  html:
    date-format: "MMMM YYYY"
    mainfont: "Source Sans Pro"
    header-includes: |
      <link href="https://cdn.jsdelivr.net/npm/charter-webfont@4.1.0/charter.min.css" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Merriweather:ital,opsz,wght@0,18..144,300..900;1,18..144,300..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
      <link href="https://fonts.cdnfonts.com/css/palatino" rel="stylesheet">
      <script src="/script.js"></script>

    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    # fontsize: 1.1em

execute: 
  enabled: true

reference-location: margin
citation-location: margin